version: '3.8'
services:

  postgres:
    image: postgres:15
    container_name: authentication-db
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  ms-authentication:
    build:
      context: .
      dockerfile: deployment/Dockerfile
    container_name: ms-authentication
    depends_on:
      - postgres
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://authentication-db:5433/auth_db
      SPRING_R2DBC_USERNAME: auth_user
      SPRING_R2DBC_PASSWORD: auth_pass
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
